spring.application.name=movement-academy-api

spring.datasource.url=jdbc:postgresql://localhost:5432/movement_academy
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}